home assignment solution
aleksZubakov/simple-cli pull request #1
Opened 2018-03-02 01:57 UTC by aleksZubakov

2018-04-04 17:32 UTC, yurii-litvinov requested changes
- команда exit приводит к `Exception in thread "pool-1-thread-1" java.lang.NullPointerException`
- cat (по крайней мере под виндой) теряет переводы строк
- если ввести несуществующую команду, падает так, что больше на команды не реагирует :)
- надо ещё текстом описать, как всё работает, и диаграмму

2018-04-04 17:32 UTC, yurii-litvinov commented on build.gradle
> +    // reportsDir file('build/test-results/junit-platform') // this is the default
Всякие ненужные штуки из примера gradle-файла можно выкинуть

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/MainThread.java
> +public class MainThread {
По идее самому классу тоже нужны комментарии

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/MainThread.java
> +     * @param in
Пустые тэги в комментариях лучше не писать --- лучше либо не писать их вовсе, либо всё-таки написать что-нибудь про параметр

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/MainThread.java
> +     * @throws IOException
С исключениями тоже --- имеет смысл написать, при каких условиях исключение бросается

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/tokens/DoubleQuotedStringToken.java
> +     * @return raw value
Начинать комментарий прямо с тэга `@return` нехорошо, потому что так комментарий сгенерится только в раздел с детальным описанием метода и в summary класса будет пустым

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/tokens/TokenInterface.java
> +public interface TokenInterface {
Интерфейсам (и их методам) комментарии даже полезнее, чем классам, интерфейсы более важны в архитектуре

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/parser/lexems/LexemInterface.java
> + *
Мм.

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/Cat.java
> +            }
Проглатывать исключения нельзя

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/SubProcess.java
> +    Command cmd;
package-полей не бывает :)

2018-04-04 17:32 UTC, yurii-litvinov commented on src/test/java/ru/spbau/cli/environment/LexerTest.java
> +        }
А зачем ловить исключение в тесте? Всё равно на билд-сервере вывод в консоль никто особо читать не будет. Пусть упадёт уж. Либо expected добавить, если оно **должно** упасть

2018-04-04 17:32 UTC, yurii-litvinov commented on src/test/java/ru/spbau/cli/environment/ParserTest.java
> +//        List<TokenInterface> testString = new LinkedList<>();
Закомментированного кода быть не должно --- он либо не нужен и тогда удалён вообще, либо нужен и тогда оставлен либо здесь, либо в другой ветке. Иначе он быстро "протухнет" и перестанет таже компилироваться

2018-04-04 17:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/helpers/Commands.java
> +import java.util.Map;
IDEA говорит, что эти штуки не нужны

2018-05-21 09:45 UTC, aleksZubakov commented on build.gradle
> +    // reportsDir file('build/test-results/junit-platform') // this is the default
убрал

2018-05-21 09:45 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/parser/lexems/LexemInterface.java
> + *
что-то не сложилось, да

2018-05-21 09:45 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/SubProcess.java
> +    Command cmd;
готово

2018-05-21 09:47 UTC, aleksZubakov commented on src/test/java/ru/spbau/cli/environment/ParserTest.java
> +//        List<TokenInterface> testString = new LinkedList<>();
убрал

2018-05-21 09:47 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/helpers/Commands.java
> +import java.util.Map;
готово

2018-05-21 10:24 UTC, ottergottaott commented on src/main/java/ru/spbau/cli/lexer/tokens/DoubleQuotedStringToken.java
> +     * @return raw value
готово

2018-05-21 10:25 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/MainThread.java
> +     * @throws IOException
готово, вообще не очень хорошо было выкидывать из main loop исключения

2018-05-21 11:53 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/MainThread.java
> +public class MainThread {
готово

2018-05-21 11:53 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/MainThread.java
> +     * @param in
готово

2018-05-21 12:54 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/Cat.java
> +            }
готово

2018-05-21 12:54 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/lexer/tokens/TokenInterface.java
> +public interface TokenInterface {
готово

2018-05-21 12:58 UTC, aleksZubakov commented on src/test/java/ru/spbau/cli/environment/LexerTest.java
> +        }
убрал

2018-05-26 09:58 UTC, yurii-litvinov requested changes
Практически всё так, хотелось бы менее агрессивно ругаться на отсутствующую команду (stack trace выводить на такую типичную ошибку --- лишний раз пугать пользователя), и надо немного подчистить код

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/MainThread.java
> +            List<TokenInterface> tokens = null;
Оно и так null, можно явно не инициализировать

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/environment/Environment.java
> +     * @return
Такие комментарии не очень полезны

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/environment/Environment.java
> +            return "";
Тут проще `return val != null ? val : "";`

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/exceptions/IllegalInputFile.java
> +public class IllegalInputFile extends RuntimeException {
Исключениям тоже нужны комментарии

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/interploator/Interpolator.java
> +     * @param source raw input string
Тут неплохо бы общее описание метода

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/Lexer.java
> +     * @throws UnexpectedStringEnd
Про исключения надо писать, при каких условиях они бросаются. То, что они бросаются, и так видно из throws ниже

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/tokens/DoubleQuotedStringToken.java
> +     * @return String
Not very helpful

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/tokens/TokenInterface.java
> +    String getValue();
И методам тоже нужны комментарии

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/parser/lexems/LexemInterface.java
> + *
И не сложится? :)

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/Cat.java
> +
Лишние пустые строчки

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/Echo.java
> +public class Echo implements TaskInterface {
Тоже неплохо бы комментарий

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/SubProcess.java
> +                    data = in.read();
Стайлгайд рекомендует ставить фигурные скобки

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/WC.java
> +    }
Копипаст суть ересь. constructor chaining помог бы

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/WC.java
> +            FileReader file = new FileReader(fileName);
try-with-resources?

2018-05-26 09:58 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/visitor/Visitor.java
> +public interface Visitor {
И тут надо комментарий.

2018-05-26 11:51 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/MainThread.java
> +            List<TokenInterface> tokens = null;
мне кажется, что человеку, который читает код, так проще хотя бы визуально(чем нагляднее, тем лучше, кмк).
в общем, это тема для холивара, если Вы не против, оставлю так

2018-05-26 11:51 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/environment/Environment.java
> +     * @return
окей, убираю

2018-05-26 11:52 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/environment/Environment.java
> +            return "";
хорошо, сделал проще:)

2018-05-26 11:54 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/lexer/Lexer.java
> +     * @throws UnexpectedStringEnd
готово

2018-05-26 11:55 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/lexer/tokens/DoubleQuotedStringToken.java
> +     * @return String
окей, тоже убираю(но мне казалось, что пользователю это как раз может помочь, т.к. не совсем ясно что оно должно вернуть)

2018-05-26 11:56 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/Cat.java
> +
fixed

2018-05-26 11:57 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/SubProcess.java
> +                    data = in.read();
fixed

2018-05-26 11:57 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/WC.java
> +    }
fixed

2018-05-26 11:59 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/taskmanager/tasks/WC.java
> +            FileReader file = new FileReader(fileName);
fixed

2018-05-26 12:06 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/visitor/Visitor.java
> +public interface Visitor {
done

2018-05-26 12:20 UTC, ottergottaott commented on src/main/java/ru/spbau/cli/taskmanager/tasks/Echo.java
> +public class Echo implements TaskInterface {
done

2018-05-26 12:25 UTC, ottergottaott commented on src/main/java/ru/spbau/cli/lexer/tokens/TokenInterface.java
> +    String getValue();
done

2018-05-26 12:26 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/interploator/Interpolator.java
> +     * @param source raw input string
done

2018-05-26 12:31 UTC, aleksZubakov commented on src/main/java/ru/spbau/cli/exceptions/IllegalInputFile.java
> +public class IllegalInputFile extends RuntimeException {
done

2018-05-26 13:09 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/MainThread.java
> +            List<TokenInterface> tokens = null;
Мне как человеку с C++-бэкграундом явная инициализация самому приятнее. Но вообще, надо отвыкать :)

2018-05-26 13:10 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/tokens/DoubleQuotedStringToken.java
> +     * @return String
так этот комментарий ничего не добавляет к и так написанному в объявлении метода

2018-05-26 13:12 UTC, yurii-litvinov approved these changes
Окей, зачтена

2018-05-26 13:12 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/environment/Environment.java
> -     */
Да не, вообще убирать комментарий было не надо, достаточно было удалить ненужные пустые тэги. У общего описания есть всё-таки какая-то ценность.

2018-05-26 13:12 UTC, yurii-litvinov commented on src/main/java/ru/spbau/cli/lexer/tokens/TokenInterface.java
> +public interface TokenInterface {
Самому интерфейсу комментарий даже нужнее, чем методам

2018-05-28 14:39 UTC, merged